### ISSUE TITLE
变量问题

### ISSUE THREAD

**Issue by zhonghuazhi** [dyc87112/SpringCloud-Learning#18]
https://github.com/dyc87112/SpringCloud-Learning/blob/72e36f4da9688412c33dcf18242e2d2f5ad03165/4-Finchley/alibaba-nacos-discovery-server/src/main/java/com/didispace/alibaba/nacos/discovery/server/TestApplication.java#L28

此处 log 无法使用 ？

**Comment by dyc87112** [comment]
Lombok了解一下 ： http://blog.didispace.com/java-lombok-1/
