### ISSUE TITLE
Brixton版config-client-eureka 

### ISSUE THREAD

**Issue by jsonfast** [dyc87112/SpringCloud-Learning#34]
client中的TestController Spring.value中的from报错

**Comment by dyc87112** [comment]
应该是是你的配置中心配置有问题，没获取到配置，所以没法注入这个配置项

**Comment by jsonfast** [comment]
不应该啊，基本都是按照你的教程配置的。。。

**Comment by jsonfast** [comment]
已解决，原因是配置文件名字前缀重复都是application，更换就可以
